Update thank_you.yml

diff --git a/.github/workflows/thank_you.yml b/.github/workflows/thank_you.yml
--- a/.github/workflows/thank_you.yml
+++ b/.github/workflows/thank_you.yml
@@ -26,3 +26,7 @@ jobs:
           echo "Error posting thank-you message. Response: $response"
           exit 1
         fi
+
+          echo "Error posting thank-you message. Response: $response"
+          exit 1
+        fi
